### ISSUE TITLE
Could you add range functions

### ISSUE THREAD

**Issue by boris-smidt-klarrio** [ewencp/golang-iterators-benchmark#3]
Its a pretty cool benchmark you have here and i really wonder how the new range-functions compare to the iterators listed here.

**Comment by ewencp** [comment]
Added in https://github.com/ewencp/golang-iterators-benchmark/commit/ae5273146d4810df572247cf5984fc1d6d47ec2d, and I updated the README with a sample run (Apple M2 Max, 64GB).

I also added some explanation to the README of the different iterator types, as well as a note at the bottom that explains why, even though they seem functionally equivalent, the CallbackIterator outperforms the BuiltinPushIterator -- the built-in push iterator implementation has to handle `break` and stopping iteration (which in this case requires no real cleanup but potentially could require e.g. cleaning up resources such as files, sockets, or goroutines). That means internally it has at least an extra conditional and function call if it hits that case.

There are also 2 versions of using the pull-iteration style. The first just uses the `iter.Pull` wrapper, which uses channels in the general case and therefore has similar performance to the BufferedChannel test since they are basically equivalent behind the scenes. The second manually implements the `next()` and `stop()` functions required by the pull-based model in order to avoid the overhead of goroutines/channels and is functionally equivalent to the ClosureIterator aside from some minor interface differences (ClosureIterator returns `has_next` to indicate if there is another item, a la Java iterators, whereas presumably to avoid blocking on having the next element the golang interface returns `ok` on `next()` if there is an element when trying to actually get the next element; and obviously ClosureIterator doesn't support `stop()` as mentioned before).

I actually find the decision to make push-based the default somewhat surprising -- it's very easy to convert any generic pull-based iterator into a push-based one automatically without introducing a goroutine/channels, but converting any generic unknown push-based iterator to a pull-based one seems like it would require introducing that overhead and inefficiency. But since I haven't followed golang development in years I'm not familiar with all the considerations involved. I don't think I've seen that design decision made in any other broadly-used language.

**Comment by boris-smidt-klarrio** [comment]
Thank you,  its interesting to see the results.

> I actually find the decision to make push-based the default somewhat surprising 
I suspect because it is oke to block using go routines it seems that a push based iterator seems more fitting.
So it works more like Unix pipes 'cat x | less'  is also push based.

One advantage is that since the push gives a bool back, it knows that the iteration is done so the cleanup can be done when a 'break' is called. Unlike iterators where you might have to fully iterate over the stream or explicitly have a close.

Tracing back it seems that the main idea started here:
https://research.swtch.com/coro

And another reason is golang can't do `(* obj)map[A,B](a A) B` so introducing iterators would make it that you have to include map and other 'functional like' paradigms. I suspect they want to stay purely imperative and preferred to add compiler level sugar instead.
